version: "2"
authtoken: 2wZeLwFXG4pCwNhiO9gSRX9b29J_212fqXWTG3gSC8sNrRNbN  # Replace with your actual ngrok auth token
tunnels:
  whatsapp:
    addr: 3001  # Changed to point to localhost:3001 where our server is running
    proto: http
    domain: annually-dashing-dolphin.ngrok-free.app 